#!/bin/bash
set -e
name="psi4nnmp2"
st_version="010"
version="0.2.0"

case $1 in
--name)
        echo $name
        ;;
--version)
        echo $version
        ;;
--install)
        mkdir -p $PREFIX/python
        garden with -c -m simtools-dependencies/${st_version}/lib-python pip install . --install-option="--prefix=$PREFIX" \
                --install-option="--install-lib=$PREFIX/python" \
                --install-option="--install-scripts=$PREFIX/bin"

        # Create a /bin gardenfile with prereqs
        python -c 'print "\n".join("prereq %s" % line.strip() for line in open("garden-prereq.txt"))' >> $GARDENDIR/bin
cat >> $GARDENDIR/bin <<EOF
prepend-path PYTHONPATH       $PREFIX/python
EOF

        # Create ModulesHelp
cat >> $PREFIX/ModulesHelp <<EOF
Release notes:
0.1 - First cut
0.2 - Add ability to turn off certain portions of the calculation

$name - Neural network MP2 plugin for PSI4
Version $version

EOF

        ;;
esac
set +e
