#!/bin/bash
set -e
name="psi4-sns-mp2"
PKG_VERSION="1.0"
HELPER_VERSION=01c7
VERSION=${PKG_VERSION}-${HELPER_VERSION}

PYTHON=desres-python/2.7.13-01c7

case $1 in
--name)
        echo $name
        ;;
--version)
        echo $VERSION
        ;;
--install)
        mkdir -p $PREFIX/python
        garden with -c -m $PYTHON/bin pip install . --install-option="--prefix=$PREFIX" \
                --install-option="--install-lib=$PREFIX/python" \
                --install-option="--install-scripts=$PREFIX/bin"

        # Create a /bin gardenfile with prereqs
        python -c 'print "\n".join("prereq %s" % line.strip() for line in open("garden-prereq.txt"))' >> $GARDENDIR/bin
cat >> $GARDENDIR/bin <<EOF
prepend-path PYTHONPATH       $PREFIX/python
EOF

        # Create ModulesHelp
cat >> $PREFIX/ModulesHelp <<EOF
Release notes:
0.1 - First cut
0.2 - Add ability to turn off certain portions of the calculation
0.2.1 - Fix sapt printing
0.2.2 - Fix sapt reporting input.method == 'DF-MP2'. It now reports input.method == 'SAPT0'
1.0.0 - Incorporate neural network into plugin

$name - Spin-network-scaled MP2 plugin for PSI4
Version $version

EOF

        ;;
esac
set +e
